### ISSUE TITLE
Error when attempting to create a facebook raffle

### ISSUE THREAD

**Issue by Mariocj89** [etcaterva/EchaloASuerte#667]
We have had multiple times already an error when some people try to create a shared facebook raffle.

Seems there is no space between the list of participants, might be an issue when decoding them

Logs:
```
[20160521 08:48:02] DEBUG echaloasuerte.access.logging_mw.process_request | User 'AnonymousUser' requests '/draw/new/raffle/shared/' with GET: <QueryDict: {u'is_shared': [u'False'], u'title': [u'Sorteo'], u'participants': [u'Ciisco krasstt Oliver Benabente Monster Dmtg Nicanor Fuentes Ezequiel Cano like Abiange kyu Sammuel Narvaez Beard YT Cristian Bay Samaiko Mejia Cama Leon Aguirre Cesar Nano Valdez Hizaki Akamaru Diego Gomez'], u'registration_requirement': [u'login'], u'prices': [u'Banner'], u'registration_type': [u'facebook']}> and POST: <QueryDict: {}>, body: 
[20160521 08:48:02] DEBUG echaloasuerte.common._ | Calling: create_draw with args: [{'post': <QueryDict: {}>, 'user': None, 'get': <QueryDict: {u'is_shared': [u'False'], u'title': [u'Sorteo'], u'participants': [u'Ciisco krasstt Oliver Benabente Monster Dmtg Nicanor Fuentes Ezequiel Cano like Abiange kyu Sammuel Narvaez Beard YT Cristian Bay Samaiko Mejia Cama Leon Aguirre Cesar Nano Valdez Hizaki Akamaru Diego Gomez'], u'registration_requirement': [u'login'], u'prices': [u'Banner'], u'registration_type': [u'facebook']}>}], and kwargs {'draw_type': u'raffle', 'is_shared': True}
[20160521 08:48:02] DEBUG echaloasuerte.views.create_draw | Serving view to create a draw: raffle
[20160521 08:48:02] INFO echaloasuerte.exception_mdw.process_exception | Processing unhandled exception tuple index out of range
[20160521 08:48:02] INFO echaloasuerte.exception_mdw.process_exception | Exception not handled, propagating...
[20160521 08:48:02] ERROR echaloasuerte.exception_mdw.process_exception | tuple index out of range
Traceback (most recent call last):
  File "/data/apache/serve/echaloasuerte/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/apache/serve/echaloasuerte/web-app/web/common.py", line 144, in _
    return func(*args, **kwargs)
  File "/data/apache/serve/echaloasuerte/web-app/web/views.py", line 112, in create_draw
    initial=initial)
  File "/data/apache/serve/echaloasuerte/web-app/server/draw_factory.py", line 77, in create_form                                               
    form = form_class(*args, **kwargs)
  File "/data/apache/serve/echaloasuerte/web-app/server/forms/raffle_form.py", line 29, in __init__
    kwargs['initial']['participants'] = [u'{{{0}:{1}}}'.format(*participant_details) for participant_details in kwargs['initial']['participants']]
IndexError: tuple index out of range
```

**Comment by Mariocj89** [comment]
Not sure how can they craete a facebook draw with participants though....

**Comment by Mariocj89** [comment]
Reproduced:

Start to create a restricted draw, enter participans space separated and change to facebook. 

The participant lists is not cleaned up
